# Generated by Django 5.2.14 on 2026-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
