# Generated by Django 5.2.14 on 2026-05-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('tagline', models.CharField(help_text='One-line value prop shown on service cards.', max_length=180)),
                ('summary', models.TextField(help_text='2-3 sentences for the services overview page.')),
                ('body_markdown', models.TextField(blank=True, help_text='Full markdown content for the service detail page.')),
                ('icon', models.CharField(blank=True, help_text="Heroicon name or symbol (e.g. 'shield-check').", max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this service on the Home page.')),
                ('is_published', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
