# Generated by Django 5.2.14 on 2026-05-15 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('timezone_label', models.CharField(blank=True, help_text='Free-form timezone label from the client (e.g. America/New_York).', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_inquiries', to='pages.service')),
            ],
            options={
                'verbose_name': 'Booking inquiry',
                'verbose_name_plural': 'Booking inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
