# Generated by Django 5.2.14 on 2026-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_booking_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='attribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
