# Generated by Django 5.2.14 on 2026-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="attribution",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
